package com.mir.news.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.mir.news.model.Article;
import com.mir.news.service.ArticleLocalServiceUtil;

/**
 * The extended model base implementation for the Article service. Represents a row in the &quot;article&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArticleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArticleImpl
 * @see com.mir.news.model.Article
 * @generated
 */
public abstract class ArticleBaseImpl extends ArticleModelImpl
    implements Article {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a article model instance should use the {@link Article} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ArticleLocalServiceUtil.addArticle(this);
        } else {
            ArticleLocalServiceUtil.updateArticle(this);
        }
    }
}
