package com.mir.news.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.mir.news.model.Review;
import com.mir.news.service.ReviewLocalServiceUtil;

/**
 * The extended model base implementation for the Review service. Represents a row in the &quot;review&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReviewImpl
 * @see com.mir.news.model.Review
 * @generated
 */
public abstract class ReviewBaseImpl extends ReviewModelImpl implements Review {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a review model instance should use the {@link Review} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ReviewLocalServiceUtil.addReview(this);
        } else {
            ReviewLocalServiceUtil.updateReview(this);
        }
    }
}
