package com.mir.news.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Review service. Represents a row in the &quot;review&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mir.news.model.impl.ReviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mir.news.model.impl.ReviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Review
 * @see com.mir.news.model.impl.ReviewImpl
 * @see com.mir.news.model.impl.ReviewModelImpl
 * @generated
 */
public interface ReviewModel extends BaseModel<Review> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a review model instance should use the {@link Review} interface instead.
     */

    /**
     * Returns the primary key of this review.
     *
     * @return the primary key of this review
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this review.
     *
     * @param primaryKey the primary key of this review
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the review ID of this review.
     *
     * @return the review ID of this review
     */
    public long getReviewId();

    /**
     * Sets the review ID of this review.
     *
     * @param reviewId the review ID of this review
     */
    public void setReviewId(long reviewId);

    /**
     * Returns the reviewer ID of this review.
     *
     * @return the reviewer ID of this review
     */
    public long getReviewerId();

    /**
     * Sets the reviewer ID of this review.
     *
     * @param reviewerId the reviewer ID of this review
     */
    public void setReviewerId(long reviewerId);

    /**
     * Returns the name of this review.
     *
     * @return the name of this review
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this review.
     *
     * @param name the name of this review
     */
    public void setName(String name);

    /**
     * Returns the text of this review.
     *
     * @return the text of this review
     */
    @AutoEscape
    public String getText();

    /**
     * Sets the text of this review.
     *
     * @param text the text of this review
     */
    public void setText(String text);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.mir.news.model.Review review);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.mir.news.model.Review> toCacheModel();

    @Override
    public com.mir.news.model.Review toEscapedModel();

    @Override
    public com.mir.news.model.Review toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
